version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm
      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - FRONTEND_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY_NAME
      - BACKEND_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_BACKEND_REPOSITORY_NAME
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
  build:
    commands:
      - echo "Building the frontend Docker image..."
      - >
        docker build
        --build-arg TURBO_TOKEN=${TURBO_TOKEN}
        --build-arg TURBO_TEAM=${TURBO_TEAM}
        --build-arg NEXT_PUBLIC_CLIENT_SECRET=${NEXT_PUBLIC_CLIENT_SECRET}
        --build-arg NEXT_PUBLIC_INVOKE_URL=${NEXT_PUBLIC_INVOKE_URL}
        --build-arg NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}
        --build-arg NEXT_PUBLIC_CLARITY=${NEXT_PUBLIC_CLARITY}
        --build-arg NEXT_PUBLIC_GTM=${NEXT_PUBLIC_GTM}
        --cache-from $FRONTEND_REPO:cache
        -t $FRONTEND_REPO:$IMAGE_TAG
        -f apps/frontend/Dockerfile .
      - echo "Building the backend Docker image..."
      - >
        docker build
        --build-arg TURBO_TOKEN=${TURBO_TOKEN}
        --build-arg TURBO_TEAM=${TURBO_TEAM}
        --cache-from $BACKEND_REPO:cache
        -t $BACKEND_REPO:$IMAGE_TAG
        -f apps/backend/Dockerfile .
  post_build:
    commands:
      - echo "Pushing the frontend Docker image to ECR..."
      - docker tag $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_REPO:cache
      - docker push $FRONTEND_REPO:$IMAGE_TAG
      - docker push $FRONTEND_REPO:cache
      - echo "Pushing the backend Docker image to ECR..."
      - docker tag $BACKEND_REPO:$IMAGE_TAG $BACKEND_REPO:cache
      - docker push $BACKEND_REPO:$IMAGE_TAG
      - docker push $BACKEND_REPO:cache
      - echo "Writing frontend image definitions file..."
      - printf '[{"name":"frontend-container","imageUri":"%s"}]' $FRONTEND_REPO:$IMAGE_TAG > imagedefinitions-frontend.json
      - echo "Writing backend image definitions file..."
      - printf '[{"name":"backend-container","imageUri":"%s"}]' $BACKEND_REPO:$IMAGE_TAG > imagedefinitions-backend.json
artifacts:
  files:
    - imagedefinitions-frontend.json
    - imagedefinitions-backend.json
cache:
  paths:
    - node_modules/**/*
    - .turbo/**/*
    - /root/.cache/docker/**/*
